# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c7b8ce99727e8e441ae37ebb14c91a07433c88ed15410170a3c274f0dc7a6a41c913e849cfdaf14024de3715aa8ae42769b587a362fcacd12f06c8e661be2d6

test:
  secret_key_base: 9cc00c8c5d6587f2b3badb4780cdcdbc0f78db5d26f678263aa4c5c3e832590ec0fdacb955f5a2a845ecbf847a770579f72237ee024bb8a19e92f19b9970afee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
