defaults: &defaults
  :verbose: true
  :concurrency: 20
  :logfile: ./log/sidekiq.log
  :timeout: 30
  :queues:
    - [default]
    - [ratings_average]
    - [ratings_mail]
development:
  <<: *defaults

test:
  <<: *defaults